apiVersion: v1
kind: Secret
metadata:
  name: usecase-secret
  namespace: "{{ K8S_NAMESPACE }}"
type: Opaque
stringData:
  API_KEY: "{{ API_KEY }}"
  NICEGUI_STORAGE_SECRET: "{{ NICEGUI_STORAGE_SECRET }}"