apiVersion: v1
kind: Service
metadata:
  name: usecase-ai
  namespace: "{{ K8S_NAMESPACE }}"
spec:
  selector:
    app: usecase-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP