apiVersion: v1
kind: ConfigMap
metadata:
  name: usecase-config
  namespace: "{{ K8S_NAMESPACE }}"
data:
  MODEL_NAME: "gpt-oss-120b"
  WORKFLOW_MODE: "production"
  LOG_LEVEL: "info"
  TOOLBOX_BASE_URL: "https://models.mylab.th-luebeck.dev/v1"
  MAX_TOKENS: "2048"