apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usecase-ai
  namespace: "{{ K8S_NAMESPACE }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
    - host: usecase-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: usecase-ai
                port:
                  number: 80
  tls:
    - hosts:
        - usecase-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
      secretName: usecase-tls